[package]
name = "drill"
version = "0.9.1"
authors = ["Ferran Basora <fcsonline@gmail.com>"]
description = "Drill is a HTTP load testing application written in Rust inspired by Ansible syntax"
repository = "https://github.com/fcsonline/drill"
keywords = ["performance", "http", "ansible", "jmeter"]
license = "GPL-3.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.6.1", features = ["cargo"] }
colored = "3.1.1"
csv = "1.4.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_yaml = "0.9.34"
url = "2.5.8"
linked-hash-map = "0.5.6"
tokio = { version = "1.52.3", features = ["time", "net"] }
reqwest = { version = "0.13.4", features = ["cookies", "hickory-dns", "form", "json", "multipart"] }
async-trait = "0.1.89"
base64 = "0.22.1"
futures = "0.3.32"
lazy_static = "1.5.0"
num_cpus = "1.17.0"
rand = "0.10.1"
hdrhistogram = "7.5.4"
hex = "0.4.3"
encoding_rs = "0.8"
fake = { version = "4.0", features = ["derive", "http"] }
jsonpath_lib = "0.3.0"

[dev-dependencies]
tempfile = "3.27.0"
